In [8]:
import pandas as pd
from pandas import read_csv
from datetime import datetime
import calendar
import matplotlib.pyplot as plt

In [9]:
df_tabular = read_csv('dataset_2/air_quality_tabular.csv')
df_tabular

C:\Users\Afonso\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,date,FID,City_EN,Prov_EN,GbCity,GbProv,Field_1,ALARM,CO_Mean,CO_Min,...,PM2.5_Max,PM2.5_Std,PM10_Mean,PM10_Min,PM10_Max,PM10_Std,SO2_Mean,SO2_Min,SO2_Max,SO2_Std
0,01/01/2020,0,Beijing,Beijing,1100,11,24.0,Safe,0.792917,0.60,...,48.0,7.618394,55.000000,38.0,86.0,14.044572,6.708333,3.0,12.0,2.440614
1,01/01/2020,1,Tianjin,Tianjin,1200,12,245.0,Safe,1.157083,0.71,...,78.0,12.203995,94.500000,64.0,123.0,17.327723,14.208333,9.0,20.0,3.054766
2,01/01/2020,2,Shijiazhuang,Hebei,1301,13,228.0,Safe,1.489167,1.17,...,95.0,13.515423,135.166667,114.0,168.0,15.249772,26.208333,22.0,33.0,2.676739
3,01/01/2020,3,Tangshan,Hebei,1302,13,244.0,Safe,1.882083,1.10,...,104.0,18.350324,133.458333,91.0,192.0,30.202068,35.208333,17.0,91.0,18.009209
4,01/01/2020,4,Qinhuangdao,Hebei,1303,13,201.0,Safe,1.389583,0.78,...,64.0,9.945686,74.416667,51.0,123.0,18.511070,25.416667,15.0,44.0,5.596998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169268,24/03/2021,530800,Puer,Yunnan,530800,53,NaN,Safe,0.575000,0.40,...,48.0,13.438065,45.666667,6.0,87.0,27.025708,4.250000,3.0,20.0,3.319764
169269,24/03/2021,640500,Zhongwei,Ningxia,640500,64,NaN,Danger,0.389583,0.15,...,73.0,11.246913,155.375000,118.0,241.0,36.133794,11.375000,5.0,23.0,5.368213
169270,24/03/2021,652801,Kuerle,Xinjiang,652801,65,NaN,Safe,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169271,24/03/2021,659001,Shihezi,Xinjiang,659001,65,NaN,Danger,0.639583,0.40,...,56.0,18.743703,154.083333,34.0,323.0,97.537137,7.208333,5.0,11.0,1.471370
169272,24/03/2021,659004,Wujiaqu,Xinjiang,659004,65,NaN,Danger,0.797917,0.40,...,63.0,14.898732,223.791667,34.0,380.0,104.250891,7.416667,6.0,15.0,1.998263

In [10]:
df_timeseries = read_csv('dataset_2/air_quality_timeseries.csv')
df_timeseries

           DATE  AQI_BEIJING
0    01/01/2020    51.958333
1    02/01/2020    70.375000
2    03/01/2020    70.250000
3    04/01/2020    60.750000
4    05/01/2020    86.041667
..          ...          ...
444  20/03/2021    83.041667
445  21/03/2021    32.125000
446  22/03/2021   129.166667
447  23/03/2021    87.375000
448  24/03/2021   106.583333

[449 rows x 2 columns]

In [11]:
years = {
    '2020' : [],
    '2021' : [],
}

quarters = {
    'Q1' : [],
    'Q2' : [],
    'Q3' : [],
    'Q4' : [],
}

months = {
    'Jan' : [],
    'Feb' : [],
    'Mar' : [],
    'Apr' : [],
    'May' : [],
    'Jun' : [],
    'Jul' : [],
    'Aug' : [],
    'Sep' : [],
    'Oct' : [],
    'Nov' : [],
    'Dec' : [],
}

weekdays = {
    'Monday' : [],
    'Tuesday' : [],
    'Wednesday' : [],
    'Thursday' : [],
    'Friday' : [],
    'Saturday' : [],
    'Sunday' : [],
}

days = {
    '1' : [],
    '2' : [],
    '3' : [],
    '4' : [],
    '5' : [],
    '6' : [],
    '7' : [],
    '8' : [],
    '9' : [],
    '10' : [],
    '11' : [],
    '12' : [],
    '13' : [],
    '14' : [],
    '15' : [],
    '16' : [],
    '17' : [],
    '18' : [],
    '19' : [],
    '20' : [],
    '21' : [],
    '22' : [],
    '23' : [],
    '24' : [],
    '25' : [],
    '26' : [],
    '27' : [],
    '28' : [],
    '29' : [],
    '30' : [],
    '31' : [],
}

for day in df_timeseries.DATE:
    day = datetime.strptime(day, "%d/%m/%Y").date()
    if pd.Timestamp(day).quarter == 1:
        quarters['Q1'] += 1
    elif pd.Timestamp(day).quarter == 2:
        quarters['Q2'] += 1
    elif pd.Timestamp(day).quarter == 3:
        quarters['Q3'] += 1
    elif pd.Timestamp(day).quarter == 4:
        quarters['Q4'] += 1
    months[day.strftime('%b')] += 1
    weekdays[calendar.day_name[day.weekday()]] += 1
    days[str(day.day)] += 1